# Generated by Django 4.2.29 on 2026-03-22 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('snack', 'Snack'), ('dinner', 'Dinner')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('protein', models.FloatField()),
                ('energy', models.FloatField()),
                ('fat', models.FloatField()),
                ('carbs', models.FloatField()),
                ('sugar', models.FloatField()),
                ('fiber', models.FloatField()),
                ('calcium', models.FloatField()),
                ('iron', models.FloatField()),
                ('magnesium', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
